/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewJobIdRouteImport } from './routes/review.$jobId'
import { Route as ResultJobIdRouteImport } from './routes/result.$jobId'
import { Route as ProcessJobIdRouteImport } from './routes/process.$jobId'
import { Route as PlanJobIdRouteImport } from './routes/plan.$jobId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewJobIdRoute = ReviewJobIdRouteImport.update({
  id: '/review/$jobId',
  path: '/review/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultJobIdRoute = ResultJobIdRouteImport.update({
  id: '/result/$jobId',
  path: '/result/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessJobIdRoute = ProcessJobIdRouteImport.update({
  id: '/process/$jobId',
  path: '/process/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanJobIdRoute = PlanJobIdRouteImport.update({
  id: '/plan/$jobId',
  path: '/plan/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/upload': typeof UploadRoute
  '/plan/$jobId': typeof PlanJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/result/$jobId': typeof ResultJobIdRoute
  '/review/$jobId': typeof ReviewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/upload': typeof UploadRoute
  '/plan/$jobId': typeof PlanJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/result/$jobId': typeof ResultJobIdRoute
  '/review/$jobId': typeof ReviewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/upload': typeof UploadRoute
  '/plan/$jobId': typeof PlanJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/result/$jobId': typeof ResultJobIdRoute
  '/review/$jobId': typeof ReviewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/create'
    | '/history'
    | '/upload'
    | '/plan/$jobId'
    | '/process/$jobId'
    | '/result/$jobId'
    | '/review/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/create'
    | '/history'
    | '/upload'
    | '/plan/$jobId'
    | '/process/$jobId'
    | '/result/$jobId'
    | '/review/$jobId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/create'
    | '/history'
    | '/upload'
    | '/plan/$jobId'
    | '/process/$jobId'
    | '/result/$jobId'
    | '/review/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  CreateRoute: typeof CreateRoute
  HistoryRoute: typeof HistoryRoute
  UploadRoute: typeof UploadRoute
  PlanJobIdRoute: typeof PlanJobIdRoute
  ProcessJobIdRoute: typeof ProcessJobIdRoute
  ResultJobIdRoute: typeof ResultJobIdRoute
  ReviewJobIdRoute: typeof ReviewJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$jobId': {
      id: '/review/$jobId'
      path: '/review/$jobId'
      fullPath: '/review/$jobId'
      preLoaderRoute: typeof ReviewJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$jobId': {
      id: '/result/$jobId'
      path: '/result/$jobId'
      fullPath: '/result/$jobId'
      preLoaderRoute: typeof ResultJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/$jobId': {
      id: '/process/$jobId'
      path: '/process/$jobId'
      fullPath: '/process/$jobId'
      preLoaderRoute: typeof ProcessJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$jobId': {
      id: '/plan/$jobId'
      path: '/plan/$jobId'
      fullPath: '/plan/$jobId'
      preLoaderRoute: typeof PlanJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  CreateRoute: CreateRoute,
  HistoryRoute: HistoryRoute,
  UploadRoute: UploadRoute,
  PlanJobIdRoute: PlanJobIdRoute,
  ProcessJobIdRoute: ProcessJobIdRoute,
  ResultJobIdRoute: ResultJobIdRoute,
  ReviewJobIdRoute: ReviewJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
